/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.furnisoft.views;

import com.furnisoft.pojos.Hardwares;
import com.furnisoft.pojos.StockDetails;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author koju5658
 */
public class SingleStockDetails extends javax.swing.JFrame {

    private Hardwares hardware;
    private List<StockDetails> stockDetails;
    public SingleStockDetails() {
        initComponents();
        this.hardware = new Hardwares();
        this.stockDetails = new ArrayList<StockDetails>();
    }
    public void setStockDetails(Hardwares hardware){
        this.hardware = hardware;
        txtStockDetail.setText("All Stock Details of "+hardware.getHardwareName());
        this.displayStockDetailsInTable();
    }
    private void displayStockDetailsInTable(){
        DefaultTableModel model = (DefaultTableModel) stockDetailsTable.getModel();
        model.setRowCount(0);
        
        JTable table = new JTable();
        table.setModel(model);
        Object rowData[] = new Object[6];
     
        long i=1;
        this.stockDetails = this.hardware.getStockDetails();
        Collections.reverse(this.stockDetails);
        for(StockDetails stockDetails : this.stockDetails)
        {
            rowData[0] = i;
            rowData[1] = stockDetails.getId();
            rowData[2] = stockDetails.getAction();
            rowData[3] = stockDetails.getQuantity();
            rowData[4] = stockDetails.getComment();
            rowData[5] = stockDetails.getRegDate();
            model.addRow(rowData);
            i++;
        }
        Collections.reverse(this.stockDetails);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtStockDetail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stockDetailsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Single Stock Detail");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel5.setBackground(new java.awt.Color(153, 0, 153));

        txtStockDetail.setBackground(new java.awt.Color(153, 0, 153));
        txtStockDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtStockDetail.setForeground(new java.awt.Color(255, 255, 255));
        txtStockDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtStockDetail.setText("All Stock Details");
        txtStockDetail.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtStockDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txtStockDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        stockDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "S.N", "ID", "Action", "Quantity", "Comment", "Registered Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(stockDetailsTable);
        if (stockDetailsTable.getColumnModel().getColumnCount() > 0) {
            stockDetailsTable.getColumnModel().getColumn(0).setMinWidth(40);
            stockDetailsTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            stockDetailsTable.getColumnModel().getColumn(0).setMaxWidth(100);
            stockDetailsTable.getColumnModel().getColumn(1).setMinWidth(40);
            stockDetailsTable.getColumnModel().getColumn(1).setPreferredWidth(60);
            stockDetailsTable.getColumnModel().getColumn(1).setMaxWidth(100);
            stockDetailsTable.getColumnModel().getColumn(2).setMinWidth(60);
            stockDetailsTable.getColumnModel().getColumn(2).setPreferredWidth(60);
            stockDetailsTable.getColumnModel().getColumn(2).setMaxWidth(60);
            stockDetailsTable.getColumnModel().getColumn(3).setMinWidth(60);
            stockDetailsTable.getColumnModel().getColumn(3).setPreferredWidth(60);
            stockDetailsTable.getColumnModel().getColumn(3).setMaxWidth(100);
            stockDetailsTable.getColumnModel().getColumn(5).setMinWidth(120);
            stockDetailsTable.getColumnModel().getColumn(5).setPreferredWidth(120);
            stockDetailsTable.getColumnModel().getColumn(5).setMaxWidth(150);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(815, 580));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SingleStockDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SingleStockDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SingleStockDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SingleStockDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SingleStockDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable stockDetailsTable;
    private javax.swing.JLabel txtStockDetail;
    // End of variables declaration//GEN-END:variables
}
